#!/usr/bin/env python3
import os
import subprocess as s
import shutil
import stat

def run():

    os.setuid(0)
    user = os.environ["PAM_USER"]
    p = s.Popen( "id -nG {}".format( str( user ) ), shell=True, stdout=s.PIPE )
    list_groups,errors = p.communicate()
    list_groups = list_groups.decode( "utf-8" )
    p = s.Popen( "echo ~{}".format( str( user ) ), shell=True, stdout=s.PIPE )
    real_home, errors = p.communicate()
    real_home = real_home.decode( "utf-8" ).strip()
    os.makedirs( real_home, exist_ok=True )
    shutil.chown( real_home, user, "nogroup" )
    current_mode = stat.S_IMODE( os.lstat( real_home ).st_mode )
    os.chmod( real_home, current_mode & ~stat.S_IRWXO )

if __name__ == "__main__":
    run()
