#!/bin/bash
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")
for x in $(find /home -mindepth 1 -maxdepth 1 -type d); do
        g="$(stat -c %G $x)"
	echo $g
        if [ "$g" = "admins" -o "$g" = "teachers" -o "$g" = "students" -o "$g" = "Domain Users" ];then
    	    chown :nogroup $x
    	    chmod o-rwx $x
        fi
done
IFS=$SAVEIFS
